// actions related to authentication
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


// actions related to loading the notifications
export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATIONS_START = 'LOAD_NOTIFICATIONS_START';
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_FAIL = 'LOAD_NOTIFICATIONS_FAIL';


// actions related to loading the user profile data
export const LOAD_PROFILE_DATA = 'LOAD_PROFILE_DATA';
export const LOAD_PROFILE_DATA_START = 'LOAD_PROFILE_DATA_START';
export const LOAD_PROFILE_DATA_SUCCESS = 'LOAD_PROFILE_DATA_SUCCESS';
export const LOAD_PROFILE_DATA_FAIL = 'LOAD_PROFILE_DATA_FAIL';


// actions related to loading the progress data
export const LOAD_PROGRESS_DATA = 'LOAD_PROGRESS_DATA';
export const LOAD_PROGRESS_DATA_START = 'LOAD_PROGRESS_DATA_START';
export const LOAD_PROGRESS_DATA_SUCCESS = 'LOAD_PROGRESS_DATA_SUCCESS';
export const LOAD_PROGRESS_DATA_FAIL = 'LOAD_PROGRESS_DATA_FAIL';

export const LOAD_PROGRESS_SUMMARY = 'LOAD_PROGRESS_SUMMARY';
export const LOAD_PROGRESS_SUMMARY_START = 'LOAD_PROGRESS_SUMMARY_START';
export const LOAD_PROGRESS_SUMMARY_SUCCESS = 'LOAD_PROGRESS_SUMMARY_SUCCESS';
export const LOAD_PROGRESS_SUMMARY_FAIL = 'LOAD_PROGRESS_SUMMARY_FAIL';


// actions related to loading courses data
export const LOAD_COURSES_DATA = 'LOAD_COURSES_DATA';
export const LOAD_COURSES_DATA_START = 'LOAD_COURSES_DATA_START';
export const LOAD_COURSES_DATA_SUCCESS = 'LOAD_COURSES_DATA_SUCCESS';
export const LOAD_COURSES_DATA_FAIL = 'LOAD_COURSES_DATA_FAIL';


// actions related to course filters 
export const FILTER_COURSES = 'FILTER_COURSES';
export const FILTER_PROGRESS = 'FILTER_PROGRESS';


// actions related to dashboard 
export const LOAD_DASHBOARD_DATA = 'LOAD_DASHBOARD_DATA';
export const LOAD_DASHBOARD_DATA_START = 'LOAD_DASHBOARD_DATA_START';
export const LOAD_DASHBOARD_DATA_SUCCESS = 'LOAD_DASHBOARD_DATA_SUCCESS';
export const LOAD_DASHBOARD_DATA_FAIL = 'LOAD_DASHBOARD_DATA_FAIL';

